version: "3.7"
services:
  app:
    build:
      args:
        user: laradockersysuser
        uid: 1000
      context: ./
      dockerfile: DockerFile
    image: laradocker
    container_name: laradocker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laradocker

  db:
    image: mysql:5.7
    container_name: laradocker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laradocker

  nginx:
    image: nginx:alpine
    container_name: laradocker-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laradocker

networks:
  laradocker:
    driver: bridge
